#  NumPy (Numerical Python) 

### Concate The Array


In [8]:
import numpy as np

#### axis 0 for vertical, axis 1 for horizontal

In [10]:
a=np.array([2,3,2])
b=np.array([3,3,3])
c=np.array([3,32,2])
print(np.concatenate([a,b,c] ,axis=0))

[ 2  3  2  3  3  3  3 32  2]


In [15]:
x=np.array([[1,2,3,4],[2,4,5,6]])
y=np.array ([[2,6,7,9],[4,8,10,12]])
z=np.array([[5,6,3,3],[3,3,3,2]])

np.concatenate((x, y,z), axis=0) # axis 0 for vertical, axis 1 for horizontal

array([[ 1,  2,  3,  4],
       [ 2,  4,  5,  6],
       [ 2,  6,  7,  9],
       [ 4,  8, 10, 12],
       [ 5,  6,  3,  3],
       [ 3,  3,  3,  2]])

#### Size tells the total number of elements in the array

In [16]:
x.size

8

#### Shape tells the dimensions of the array

In [17]:
x.shape

(2, 4)

#### Reshape allows to change the dimensions of the array

In [18]:
x.reshape((4,2)) # to reshape the array

array([[1, 2],
       [3, 4],
       [2, 4],
       [5, 6]])

In [27]:
x.reshape((2,4)) # to reshape the array

array([[1, 2, 3, 4],
       [2, 4, 5, 6]])

### newaxia is used to add a new axis to the array

In [29]:
newaxia=x[np.newaxis, np.newaxis]
newaxia.shape

(1, 1, 2, 4)

#### Expand array to increase the dimension

In [34]:
np.expand_dims(newaxia , axis=0)

array([[[[[1, 2, 3, 4],
          [2, 4, 5, 6]]]]])

In [20]:
expand_x=np.expand_dims(newaxia, axis=1)
expand_x.shape

(1, 1, 1, 1, 2, 4)