#  NumPy (Numerical Python) 

### create a zeros array with given shape and datatype

In [13]:
import numpy as np
print(np.zeros([3,2,2,2] , dtype=int )) 

[[[[0 0]
   [0 0]]

  [[0 0]
   [0 0]]]


 [[[0 0]
   [0 0]]

  [[0 0]
   [0 0]]]


 [[[0 0]
   [0 0]]

  [[0 0]
   [0 0]]]]


In [18]:
import numpy as np

# Create a zeros

zeros = np.zeros([2,3,4,6], dtype=np.int64)

print(zeros)


[[[[0 0 0 0 0 0]
   [0 0 0 0 0 0]
   [0 0 0 0 0 0]
   [0 0 0 0 0 0]]

  [[0 0 0 0 0 0]
   [0 0 0 0 0 0]
   [0 0 0 0 0 0]
   [0 0 0 0 0 0]]

  [[0 0 0 0 0 0]
   [0 0 0 0 0 0]
   [0 0 0 0 0 0]
   [0 0 0 0 0 0]]]


 [[[0 0 0 0 0 0]
   [0 0 0 0 0 0]
   [0 0 0 0 0 0]
   [0 0 0 0 0 0]]

  [[0 0 0 0 0 0]
   [0 0 0 0 0 0]
   [0 0 0 0 0 0]
   [0 0 0 0 0 0]]

  [[0 0 0 0 0 0]
   [0 0 0 0 0 0]
   [0 0 0 0 0 0]
   [0 0 0 0 0 0]]]]


### create ones array with given datatype

In [19]:
var=np.ones([3,5,6,8], dtype=np.float64)

### Empty array creation

In [ ]:
np.empty([2,4,6,8])

(array([[[[ 1.07259150e-311,  1.07259194e-311,  1.07260201e-311,
            1.07243954e-311,  1.97626258e-323,  0.00000000e+000,
                        nan,              nan],
          [-1.44037754e+304,  0.00000000e+000,  3.95252517e-323,
            1.07260201e-311,  1.07243954e-311,  9.88131292e-324,
            0.00000000e+000,              nan],
          [ 2.22329541e-322,  1.07160787e-311,  3.55727265e-322,
            3.95252517e-323,  1.07260201e-311,  1.07243954e-311,
            9.88131292e-324,  0.00000000e+000],
          [             nan,  4.15015143e-322,  1.07160787e-311,
            7.11454530e-322,  3.95252517e-323,  1.07260201e-311,
            1.07243954e-311,  9.88131292e-324],
          [ 0.00000000e+000,              nan,  2.86558075e-322,
            1.07160787e-311,  1.06718180e-321,  3.95252517e-323,
            1.07260201e-311,  1.07243954e-311],
          [ 9.88131292e-324,  0.00000000e+000,              nan,
            2.86558075e-322,  1.07160787e-311

### create Arrange array

In [9]:
np.arange(1,21,5)

array([ 1,  6, 11, 16])

In [21]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

### create linspace array

In [22]:
np.linspace(0,10,60)

array([ 0.        ,  0.16949153,  0.33898305,  0.50847458,  0.6779661 ,
        0.84745763,  1.01694915,  1.18644068,  1.3559322 ,  1.52542373,
        1.69491525,  1.86440678,  2.03389831,  2.20338983,  2.37288136,
        2.54237288,  2.71186441,  2.88135593,  3.05084746,  3.22033898,
        3.38983051,  3.55932203,  3.72881356,  3.89830508,  4.06779661,
        4.23728814,  4.40677966,  4.57627119,  4.74576271,  4.91525424,
        5.08474576,  5.25423729,  5.42372881,  5.59322034,  5.76271186,
        5.93220339,  6.10169492,  6.27118644,  6.44067797,  6.61016949,
        6.77966102,  6.94915254,  7.11864407,  7.28813559,  7.45762712,
        7.62711864,  7.79661017,  7.96610169,  8.13559322,  8.30508475,
        8.47457627,  8.6440678 ,  8.81355932,  8.98305085,  9.15254237,
        9.3220339 ,  9.49152542,  9.66101695,  9.83050847, 10.        ])

### How to Sort the array

In [11]:
a=np.linspace(1,20,10)
np.sort(a, kind="quicksort")


array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [23]:
arr=[1, 4, 2, 5, 3, 6, 8, 9, 7, 10]
np.sort(arr, kind='quicksort')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### argsort array index

In [24]:
np.argsort(arr)

array([0, 2, 4, 1, 3, 5, 8, 6, 7, 9], dtype=int64)

In [19]:

### Generate an empty 4 dimensional array fill elements in it using for loop

arr_4d = np.empty((4, 4, 4, 4))
for i in range(4):
    for j in range(4):
        for k in range(4):
            for l in range(4):
                arr_4d[i, j, k, l] = (i*j*k*l)+1
                print(arr_4d)


[[[[1.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
   [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
   [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
   [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]

  [[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
   [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
   [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
   [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]

  [[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
   [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
   [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
   [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]

  [[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
   [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
   [0.00000000e+000 0.000000