#  NumPy (Numerical Python) 

### Concate The Array


In [2]:
import numpy as np

#### axis 0 for vertical, axis 1 for horizontal

In [11]:
x=np.array([[1,2,3,4],[2,4,5,6]])
y=np.array ([[2,6,7,9],[4,8,10,12]])

np.concatenate((x, y), axis=1) # axis 0 for vertical, axis 1 for horizontal

array([[ 1,  2,  3,  4,  2,  6,  7,  9],
       [ 2,  4,  5,  6,  4,  8, 10, 12]])

#### Size tells the total number of elements in the array

In [14]:
x.size

2

#### Shape tells the dimensions of the array

In [15]:
x.shape

(2, 4)

#### Reshape allows to change the dimensions of the array

In [19]:
x.reshape((4,2)) # to reshape the array

array([[1, 2],
       [3, 4],
       [2, 4],
       [5, 6]])

In [20]:
x.reshape((2,4)) # to reshape the array

array([[1, 2, 3, 4],
       [2, 4, 5, 6]])

### newaxia is used to add a new axis to the array

In [37]:
newaxia=x[np.newaxis, np.newaxis]
newaxia.shape

(1, 1, 2, 4)

#### Expand array to increase the dimension

In [31]:
expand_x=np.expand_dims(x, axis=1)
expand_x.shape

(2, 1, 4)