# NumPy (Numerical Python) Introduction
NumPy is the fundamental package for scientific computing in Python. It serves as the foundation for many other data science and machine learning libraries like Pandas, SciPy, and scikit-learn.

##  NumPy Arrays vs. Python Lists

- **Performance**: NumPy arrays are more memory-efficient than Python lists due to their homogeneous data type. This allows NumPy to perform operations on entire arrays, rather than individual elements.

- **Convenience**: NumPy provides functions and methods that make it easier to perform mathematical operations on arrays, such as vectorized operations and broadcasting.

- **Broadcasting**: NumPy allows arrays of different shapes to be combined using broadcasting, which enables efficient computations on large arrays.

# Use Cases for NumPy Arrays

- **Numerical computations**: NumPy arrays are ideal for performing mathematical operations on large datasets. They provide high-performance, vectorized operations, and efficient memory management.

- **Data analysis**: NumPy arrays can be used to represent and manipulate large datasets, such as images, audio, and scientific data.

- **Machine learning and data science**: NumPy arrays are used in machine learning and data science libraries like Scikit-learn, TensorFlow, and PyTorch to perform numerical computations and handle large datasets efficiently.

### Lets Write First Program

In [1]:
# import libaray
import numpy as np

# create a numpy array

arr = np.array([1, 2, 3, 4, 5])

# print the array

print(arr)


[1 2 3 4 5]


## Check Dimension

In [3]:
arr1=np.array([1,2,3,4])
print("Dimensions:", arr1.ndim)


Dimension 1


### Check Shape

In [5]:
print("Shape:", str(arr1.shape))

Shape: (4,)


### Create 2D Array

In [7]:
array=np.array([[1,2,3,4],
                [5,6,7,8]])
print(array)
print("Dimensions:", array.ndim)

print("Shape:", str(array.shape))


[[1 2 3 4]
 [5 6 7 8]]
Dimensions: 2
Shape: (2, 4)


### Accessing Elements in NumPy Arrays
1. Zero-based indexing (like Python lists)
2. Supports positive and negative indices
3. Can use slicing with start:stop:step syntax



In [8]:
print(array[1, 3])

8


### Create 3D Array

In [13]:
array_1 = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],
    
    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])
print(array_1)
print("Dimensions:", array_1.ndim)

print("Shape:", array_1.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Dimensions: 3
Shape: (2, 3, 4)


### Create 4D Array

In [15]:
array_4d = np.array([
    [[[1, 2, 3, 4],
      [5, 6, 7, 8]],
     
     [[9, 10, 11, 12],
      [13, 14, 15, 16]],
     
     [[17, 18, 19, 20],
      [21, 22, 23, 24]]],
    
    [[[25, 26, 27, 28],
      [29, 30, 31, 32]],
     
     [[33, 34, 35, 36],
      [37, 38, 39, 40]],
     
     [[41, 42, 43, 44],
      [45, 46, 47, 48]]]
])

print(array_4d)

print("Dimensions:", array_4d.ndim)

print("Shape:", array_4d.shape)


[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]]]


 [[[25 26 27 28]
   [29 30 31 32]]

  [[33 34 35 36]
   [37 38 39 40]]

  [[41 42 43 44]
   [45 46 47 48]]]]
Dimensions: 4
Shape: (2, 3, 2, 4)


In [16]:
array_5d = np.array([[
    [[[1, 2, 3, 4],
      [5, 6, 7, 8]],
     
     [[9, 10, 11, 12],
      [13, 14, 15, 16]],
     
     [[17, 18, 19, 20],
      [21, 22, 23, 24]]],
    
    [[[25, 26, 27, 28],
      [29, 30, 31, 32]],
     
     [[33, 34, 35, 36],
      [37, 38, 39, 40]],
     
     [[41, 42, 43, 44],
      [45, 46, 47, 48]]]],
      [
    [[[1, 2, 3, 4],
      [5, 6, 7, 8]],
     
     [[9, 10, 11, 12],
      [13, 14, 15, 16]],
     
     [[17, 18, 19, 20],
      [21, 22, 23, 24]]],
    
    [[[25, 26, 27, 28],
      [29, 30, 31, 32]],
     
     [[33, 34, 35, 36],
      [37, 38, 39, 40]],
     
     [[41, 42, 43, 44],
      [45, 46, 47, 48]]]
]])

print(array_5d)

print("Dimensions:", array_5d.ndim)

print("Shape:", array_5d.shape)

[[[[[ 1  2  3  4]
    [ 5  6  7  8]]

   [[ 9 10 11 12]
    [13 14 15 16]]

   [[17 18 19 20]
    [21 22 23 24]]]


  [[[25 26 27 28]
    [29 30 31 32]]

   [[33 34 35 36]
    [37 38 39 40]]

   [[41 42 43 44]
    [45 46 47 48]]]]



 [[[[ 1  2  3  4]
    [ 5  6  7  8]]

   [[ 9 10 11 12]
    [13 14 15 16]]

   [[17 18 19 20]
    [21 22 23 24]]]


  [[[25 26 27 28]
    [29 30 31 32]]

   [[33 34 35 36]
    [37 38 39 40]]

   [[41 42 43 44]
    [45 46 47 48]]]]]
Dimensions: 5
Shape: (2, 2, 3, 2, 4)


### Access last Element in the 5D Array

In [17]:
print(array_5d[1,1,2,1,3])

48


### --------------------------------------- THANKS -----------------------------------------