In [75]:
import numpy as np

Task-1: Basic Array Creation & Indexing
Create a 1D NumPy array with numbers from 10 to 20.

Extract the first three elements from the array.

Modify the last element to be 100.


In [76]:
a=np.array([10,11,12,13,14,15,16,17,18,19,20])
print(a)
b=np.arange(10,21,1)
print(b)
print(a[:3])
a[-1]=100
print(a)


[10 11 12 13 14 15 16 17 18 19 20]
[10 11 12 13 14 15 16 17 18 19 20]
[10 11 12]
[ 10  11  12  13  14  15  16  17  18  19 100]


Task-2: Array Slicing & Views
Create a 1D array from 1 to 10 and extract a slice containing only even numbers.

Change an element in the slice and check if the original array is also affected.



In [77]:
c=np.array([1,2,3,4,5,6,7,8,9,10])
print(c[1:10:2])
print(c[c%2==0])
c=np.array([1,2,3,4,5,6,7,8,9,10])
print(c[0:10:2])
print(c[c%2!=0])
c[1]=9922
print(c)


[ 2  4  6  8 10]
[ 2  4  6  8 10]
[1 3 5 7 9]
[1 3 5 7 9]
[   1 9922    3    4    5    6    7    8    9   10]


Task-3: Multi-Dimensional Arrays
Create a 3×3 NumPy array filled with numbers from 1 to 9.

Retrieve the element in the second row and third column.

Extract the second column as a 1D array.


In [78]:
# a1 is already 3D
a1 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]]])
print("a1:\n", a1)
print("a1.ndim:", a1.ndim)  # 3D

# make a2 3D too
a2 = np.arange(1, 10).reshape(1, 3, 3)
print("\na2:\n", a2)
print("a2.ndim:", a2.ndim)  # 3D

print(a1[0,1,2])
print(a1[0, :, 1]) 




a1:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
a1.ndim: 3

a2:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
a2.ndim: 3
6
[2 5 8]


Task-4: Array Attributes
Create a 4×2 array of random integers from 0 to 50.

Find its shape, size, and number of dimensions.


In [79]:
# Create a 4×2 array of random integers from 0 to 50
arr = np.random.randint(0, 51, size=(4, 2))

# Print the array
print(arr)
# Shape of the array (rows, columns)
print(arr.shape)

# Total number of elements
print(arr.size)

# Number of dimensions (2D array)
print(arr.ndim)


[[ 4 45]
 [35 39]
 [38 10]
 [36 39]]
(4, 2)
8
2


Task-5: Array Creation Functions
Create a 1D array of 5 zeros, then convert it to integers.

Generate a 3×3 identity matrix.

Create an array of 10 evenly spaced numbers between 0 and 100.


In [80]:
print(np.zeros(5,dtype=int))
print(np.identity(3))
print(np.arange(0,101,10))
print(np.linspace(0,100,10))

[0 0 0 0 0]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[  0  10  20  30  40  50  60  70  80  90 100]
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]



Task-6: Sorting & Concatenation
Given arr = np.array([8, 2, 5, 1, 7]), sort the array in ascending order.

Concatenate two arrays: np.array([1, 2, 3]) and np.array([4, 5, 6]).


In [81]:
arr = np.array([8, 2, 5, 1, 7])
print(np.sort(arr , kind="quicksort"))
m=np.array([1, 2, 3]) 
n=np.array([4, 5, 6])
print(np.concatenate((m, n), axis=0)) 


[1 2 5 7 8]
[1 2 3 4 5 6]


Task-7: Reshaping & Expanding Dimensions
Create a 1D array of size 6 and reshape it into a 2×3 matrix.

Convert a 1D array into a column vector using np.newaxis.

Use np.expand_dims to convert a 1D array into a 2D row vector.

In [95]:
z=np.array([1,2,3,4,5,6])
print(z.reshape(2,3))
print(z[: ,np.newaxis])
print(np.expand_dims(z, axis=0))



[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3 4 5 6]]


In [102]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsTransformer
from sklearn.datasets import load_iris


X,y=load_iris(return_X_y=True)


X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
print(X_train.shape)

lr=LogisticRegression()
lr.fit(X_train,y_train)


(120, 4)


LogisticRegression()

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Step 1: Load the Iris dataset
X, y = load_iris(return_X_y=True)

# Step 2: Split the data (60% training, 40% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

# Step 3: Create and train the Decision Tree model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
# Step 4: mdoel.Predict on both training and testing data of xT and xT
train_preds = model.predict(X_train)
test_preds = model.predict(X_test)

# Step 5: Calculate and print accuracy score of yT,xt yt,xt
train_acc = accuracy_score(y_train, train_preds)
test_acc = accuracy_score(y_test, test_preds)

print("Training Accuracy:", train_acc)
print("Testing Accuracy:", test_acc)


0.9666666666666667
0.9666666666666667
