# NumPy (Numerical Python)

In [2]:
import numpy as np

In [ ]:
arr=np.array([10,11,12,13,14,15,16,17,18,19,20])
arr_1=np.arange(10,21,1)
print(arr)
print(arr_1)
arr[0:3]
arr[-1]=100
print(arr)

NameError: name 'np' is not defined

In [14]:
# craete 1D Numpy
num=np.arange(10,21,1)

print("Demension: ", num.ndim)
print(num)


Demension:  1
[10 11 12 13 14 15 16 17 18 19 20]


In [6]:
# exact first three elemets

print(num[0:3])


[10 11 12]


In [15]:
#modfiy the last elememts to be 100 

num[-1]=100
print(num)

[ 10  11  12  13  14  15  16  17  18  19 100]


In [18]:
# craete 1D Array from 1 to 10 and exteact a slice
num1=np.array([1,2,3,4,5,6,7,8,9,10])
extract=num1[1:11:2] 
print(extract)

[ 2  4  6  8 10]


In [19]:
# change the element in the slice and check the if the original array is also affected
extract[2]=10
print(extract)
print(num1)

[ 2  4 10  8 10]
[ 1  2  3  4  5 10  7  8  9 10]


In [59]:
# multidim
num3=np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
                [[10,11,12],
                [13,14,15],
                [16,17,18]]])
print(num3.ndim)



3


In [63]:
# retrive the elemnts from 
print(num3[1, :, 2])


[12 15 18]


In [74]:
# create the 4x2 array of random integers

num4=np.random.randint(100,150, size=(5,4))
num4

array([[104, 118, 142, 115],
       [112, 122, 149, 120],
       [140, 141, 130, 105],
       [146, 146, 122, 124],
       [128, 117, 130, 133]], dtype=int32)

In [73]:
print(num4.shape)
print(num4.size)
print(num4.ndim)

(5, 4, 5)
100
3


In [77]:
# create 1d array of 5 zeors

num5=np.ones(5)
num5.astype(int)


array([1, 1, 1, 1, 1])

In [78]:
num6=np.identity(5)
num6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [100]:
num17=np.eye(3)
num17

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
#create an array of 10 evenly spaced numbers between 0 to 100
num7=np.linspace(0,100,10,dtype=int)
num7

array([  0,  11,  22,  33,  44,  55,  66,  77,  88, 100])

In [73]:
num8=np.array([8,2,5,1,7])
np.sort(num8)


array([1, 2, 5, 7, 8])

In [71]:
num9=np.array([1,2,3])
num10=np.array([4,5,6])
sum=np.concatenate((num9,num10))
sum


array([1, 2, 3, 4, 5, 6])

In [88]:
num11=np.array([1,2,3,4,5,7])
num11.reshape((3,2))


array([[1, 2],
       [3, 4],
       [5, 7]])

In [ ]:
# convert the 1D array  vector
num12=np.array([1,2,3,4,5,6])
s=num12[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
num13=np.array([1,2,3,4,5])
np.expand_dims(num13, axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

Create a 1D NumPy array with elements from 5 to 15. Extract the first 5 elements from the array and change the last element to 50.

In [ ]:
arr1=np.array([5,6,7,8,9,10,11,12,13,14,15])
arr2=np.arange(5,16,1)
print(arr2)
print(arr2)

print(arr1[0:6])



[ 5  6  7  8  9 10 11 12 13 14 15]
[ 5  6  7  8  9 10 11 12 13 14 15]
[ 5  6  7  8  9 10]
