# NumPy (Numerical Python)

In [1]:
import numpy as np

In [4]:
arr=np.array([10,11,12,13,14,15,16,17,18,19,20])
arr_1=np.arange(10,21,1)
print(arr)
print(arr_1)

[10 11 12 13 14 15 16 17 18 19 20]
[10 11 12 13 14 15 16 17 18 19 20]


In [14]:
# craete 1D Numpy
num=np.arange(10,21,1)

print("Demension: ", num.ndim)
print(num)


Demension:  1
[10 11 12 13 14 15 16 17 18 19 20]


In [6]:
# exact first three elemets

print(num[0:3])


[10 11 12]


In [15]:
#modfiy the last elememts to be 100 

num[-1]=100
print(num)

[ 10  11  12  13  14  15  16  17  18  19 100]


In [30]:
# craete 1D Array from 1 to 10 and exteact a slice
num1=np.array([1,2,3,4,5,6,7,8,9,10])
extract=num1[1:11:2] 
print(extract)

[ 2  4  6  8 10]


In [35]:
# change the element in the slice and check the if the original array is also affected
extract[2]=10
print(extract)
print(num1)

[ 2  4 10  8 10]
[ 1  2  3  4  5 10  7  8  9 10]


In [93]:
# multidim
num3=np.array([[1,2,3],[4,5,6],[7,8,9]])

num3



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
# retrive the elemnts from 

num3[1,2]

6

In [94]:
#extract the second 1d array
num3[:,1]

array([2, 5, 8])

In [46]:
# create the 4x2 array of random integers

num4=np.random.randint(50, size=(4,2))
num4

array([[46, 26],
       [46, 19],
       [23, 30],
       [ 7, 21]])

In [47]:
print(num4.shape)
print(num4.size)
print(num4.ndim)

(4, 2)
8
2


In [59]:
# create 1d array of 5 zeors

num5=np.zeros(5)
num5.astype(int)


array([0, 0, 0, 0, 0])

In [98]:
num6=np.identity(3)
num6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [100]:
num17=np.eye(3)
num17

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [95]:
#create an array of 10 evenly spaced numbers between 0 to 100
num7=np.linspace(0,2,100)
num7

array([0.        , 0.02020202, 0.04040404, 0.06060606, 0.08080808,
       0.1010101 , 0.12121212, 0.14141414, 0.16161616, 0.18181818,
       0.2020202 , 0.22222222, 0.24242424, 0.26262626, 0.28282828,
       0.3030303 , 0.32323232, 0.34343434, 0.36363636, 0.38383838,
       0.4040404 , 0.42424242, 0.44444444, 0.46464646, 0.48484848,
       0.50505051, 0.52525253, 0.54545455, 0.56565657, 0.58585859,
       0.60606061, 0.62626263, 0.64646465, 0.66666667, 0.68686869,
       0.70707071, 0.72727273, 0.74747475, 0.76767677, 0.78787879,
       0.80808081, 0.82828283, 0.84848485, 0.86868687, 0.88888889,
       0.90909091, 0.92929293, 0.94949495, 0.96969697, 0.98989899,
       1.01010101, 1.03030303, 1.05050505, 1.07070707, 1.09090909,
       1.11111111, 1.13131313, 1.15151515, 1.17171717, 1.19191919,
       1.21212121, 1.23232323, 1.25252525, 1.27272727, 1.29292929,
       1.31313131, 1.33333333, 1.35353535, 1.37373737, 1.39393939,
       1.41414141, 1.43434343, 1.45454545, 1.47474747, 1.49494

In [73]:
num8=np.array([8,2,5,1,7])
np.sort(num8)


array([1, 2, 5, 7, 8])

In [71]:
num9=np.array([1,2,3])
num10=np.array([4,5,6])
sum=np.concatenate((num9,num10))
sum


array([1, 2, 3, 4, 5, 6])

In [80]:
num11=np.array([1,2,3,4,5,6])
num11.reshape((2,3))


array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
# convert the 1D array  vector
num12=np.array([1,2,3,4,5,6])
s=num12[:,np.newaxis]
s

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [85]:
num13=np.array([1,2,3,4,5])
np.expand_dims(num13, axis=0)

array([[1, 2, 3, 4, 5]])